=== Draagon/draagon-metaobjects/core/src/test/resources/metadata/test/produce/v1/metaobjects-model.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="https://draagon.com/schema/metamodel/simple" elementFormDefault="qualified" targetNamespace="https://draagon.com/schema/metamodel/simple">
  <xs:element name="metadata">
    <xs:complexType>
      <xs:choice maxOccurs="unbounded">
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="object"/>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="field"/>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="validator"/>
      </xs:choice>
      <xs:attribute name="package">
        <xs:simpleType>
          <xs:restriction base="xs:string"/>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="attr">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="package">
            <xs:simpleType>
              <xs:restriction base="xs:string"/>
            </xs:simpleType>
          </xs:attribute>
          <xs:attribute name="name">
            <xs:simpleType>
              <xs:restriction base="xs:string"/>
            </xs:simpleType>
          </xs:attribute>
          <xs:attribute name="type">
            <xs:simpleType>
              <xs:restriction base="xs:string"/>
            </xs:simpleType>
          </xs:attribute>
          <xs:attribute name="super">
            <xs:simpleType>
              <xs:restriction base="xs:string"/>
            </xs:simpleType>
          </xs:attribute>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="object">
    <xs:complexType>
      <xs:choice maxOccurs="unbounded">
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="attr"/>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="key"/>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="field"/>
      </xs:choice>
      <xs:attribute name="package">
        <xs:simpleType>
          <xs:restriction base="xs:string"/>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="name">
        <xs:simpleType>
          <xs:restriction base="xs:string"/>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="type">
        <xs:simpleType>
          <xs:restriction base="xs:string"/>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="super">
        <xs:simpleType>
          <xs:restriction base="xs:string"/>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="_isAbstract">
        <xs:simpleType>
          <xs:restriction base="xs:boolean"/>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="isInterface">
        <xs:simpleType>
          <xs:restriction base="xs:boolean"/>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="object">
        <xs:simpleType>
          <xs:restriction base="xs:string"/>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="proxyObject">
        <xs:simpleType>
          <xs:restriction base="xs:string"/>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="key">
    <xs:complexType>
      <xs:choice maxOccurs="unbounded">
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="attr"/>
      </xs:choice>
      <xs:attribute name="package">
        <xs:simpleType>
          <xs:restriction base="xs:string"/>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="name">
        <xs:simpleType>
          <xs:restriction base="xs:string"/>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="type">
        <xs:simpleType>
          <xs:restriction base="xs:string"/>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="super">
        <xs:simpleType>
          <xs:restriction base="xs:string"/>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="keys">
        <xs:simpleType>
          <xs:restriction base="xs:string"/>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="foreignObjectRef">
        <xs:simpleType>
          <xs:restriction base="xs:string"/>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="foreignKey">
        <xs:simpleType>
          <xs:restriction base="xs:string"/>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="field">
    <xs:complexType>
      <xs:choice maxOccurs="unbounded">
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="attr"/>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="validator"/>
      </xs:choice>
      <xs:attribute name="package">
        <xs:simpleType>
          <xs:restriction base="xs:string"/>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="name">
        <xs:simpleType>
          <xs:restriction base="xs:string"/>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="type">
        <xs:simpleType>
          <xs:restriction base="xs:string"/>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="super">
        <xs:simpleType>
          <xs:restriction base="xs:string"/>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="_isAbstract">
        <xs:simpleType>
          <xs:restriction base="xs:boolean"/>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="objectRef">
        <xs:simpleType>
          <xs:restriction base="xs:string"/>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="validator">
    <xs:complexType>
      <xs:choice maxOccurs="unbounded">
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="attr"/>
      </xs:choice>
      <xs:attribute name="package">
        <xs:simpleType>
          <xs:restriction base="xs:string"/>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="name">
        <xs:simpleType>
          <xs:restriction base="xs:string"/>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="type">
        <xs:simpleType>
          <xs:restriction base="xs:string"/>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="super">
        <xs:simpleType>
          <xs:restriction base="xs:string"/>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="mask">
        <xs:simpleType>
          <xs:restriction base="xs:string"/>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="min">
        <xs:simpleType>
          <xs:restriction/>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="max">
        <xs:simpleType>
          <xs:restriction/>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="minSize">
        <xs:simpleType>
          <xs:restriction/>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="maxSize">
        <xs:simpleType>
          <xs:restriction/>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Draagon/draagon-metaobjects/core/src/test/resources/metadata/test/produce/v1/meta.vegetable.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>

<metadata
        xmlns="https://draagon.com/schema/metamodel/simple"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://draagon.com/schema/metamodel/simple metaobjects-model.xsd"
        package="produce::v1::vegetable">

    <!-- Vegetable -->
    <object name="Vegetable" type="pojo" _isAbstract="true">

        <key name="primary" keys="id"/>
        <key type="foreign" name="basketKey" keys="basketId" foreignObjectRef="..::container::Basket"/>

        <attr name="object">com.draagon.meta.test.produce.v1.Vegetable</attr>

        <!-- Id -->
        <field name="id" super="..::common::id"/>

        <!-- Name -->
        <field name="name" super="..::common::name"/>

        <!-- BasketId -->
        <field name="basketId" super="..::common::id"/>

        <!-- Length -->
        <field name="length" type="int"/>

        <!-- Weight -->
        <field name="weight" type="int"/>

    </object>

    <!-- Tomato -->
    <object name="Tomato" super="Vegetable">

        <attr name="object">com.draagon.meta.test.produce.v1.Tomato</attr>

    </object>

</metadata>
