=== Draagon/draagon-metaobjects/core/src/test/resources/metadata/test/produce/v1/produce-v1-model.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="https://draagon.com/schema/metamodel/produce/v1" elementFormDefault="qualified" targetNamespace="https://draagon.com/schema/metamodel/produce/v1">
  <xs:element name="metadata">
    <xs:complexType>
      <xs:choice maxOccurs="unbounded">
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="object"/>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="field"/>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="validator"/>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="attr"/>
      </xs:choice>
      <xs:attribute name="package">
        <xs:simpleType>
          <xs:restriction base="xs:string"/>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="farmName">
        <xs:simpleType>
          <xs:restriction base="xs:string"/>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="attr">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="package">
            <xs:simpleType>
              <xs:restriction base="xs:string"/>
            </xs:simpleType>
          </xs:attribute>
          <xs:attribute name="name">
            <xs:simpleType>
              <xs:restriction base="xs:string"/>
            </xs:simpleType>
          </xs:attribute>
          <xs:attribute name="type">
            <xs:simpleType>
              <xs:restriction base="xs:string">
                <xs:enumeration value="string"/>
                <xs:enumeration value="stringArray"/>
                <xs:enumeration value="properties"/>
                <xs:enumeration value="class"/>
                <xs:enumeration value="boolean"/>
                <xs:enumeration value="int"/>
              </xs:restriction>
            </xs:simpleType>
          </xs:attribute>
          <xs:attribute name="super">
            <xs:simpleType>
              <xs:restriction base="xs:string"/>
            </xs:simpleType>
          </xs:attribute>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="object">
    <xs:complexType>
      <xs:choice maxOccurs="unbounded">
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="attr"/>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="key"/>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="field"/>
      </xs:choice>
      <xs:attribute name="package">
        <xs:simpleType>
          <xs:restriction base="xs:string"/>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="name">
        <xs:simpleType>
          <xs:restriction base="xs:string"/>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="type">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="pojo"/>
            <xs:enumeration value="map"/>
            <xs:enumeration value="proxy"/>
            <xs:enumeration value="data"/>
            <xs:enumeration value="value"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="super">
        <xs:simpleType>
          <xs:restriction base="xs:string"/>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="_isAbstract">
        <xs:simpleType>
          <xs:restriction base="xs:boolean"/>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="isInterface">
        <xs:simpleType>
          <xs:restriction base="xs:boolean"/>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="isEmbedded">
        <xs:simpleType>
          <xs:restriction base="xs:boolean"/>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="object">
        <xs:simpleType>
          <xs:restriction base="xs:string"/>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="proxyObject">
        <xs:simpleType>
          <xs:restriction base="xs:string"/>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="key">
    <xs:complexType>
      <xs:choice maxOccurs="unbounded">
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="attr"/>
      </xs:choice>
      <xs:attribute name="package">
        <xs:simpleType>
          <xs:restriction base="xs:string"/>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="name">
        <xs:simpleType>
          <xs:restriction base="xs:string"/>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="type">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="primary"/>
            <xs:enumeration value="secondary"/>
            <xs:enumeration value="foreign"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="super">
        <xs:simpleType>
          <xs:restriction base="xs:string"/>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="keys">
        <xs:simpleType>
          <xs:restriction base="xs:string"/>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="foreignObjectRef">
        <xs:simpleType>
          <xs:restriction base="xs:string"/>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="foreignKey">
        <xs:simpleType>
          <xs:restriction base="xs:string"/>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="field">
    <xs:complexType>
      <xs:choice maxOccurs="unbounded">
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="attr"/>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="validator"/>
      </xs:choice>
      <xs:attribute name="package">
        <xs:simpleType>
          <xs:restriction base="xs:string"/>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="name">
        <xs:simpleType>
          <xs:restriction base="xs:string"/>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="type">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="boolean"/>
            <xs:enumeration value="byte"/>
            <xs:enumeration value="short"/>
            <xs:enumeration value="int"/>
            <xs:enumeration value="long"/>
            <xs:enumeration value="float"/>
            <xs:enumeration value="double"/>
            <xs:enumeration value="string"/>
            <xs:enumeration value="date"/>
            <xs:enumeration value="stringArray"/>
            <xs:enumeration value="object"/>
            <xs:enumeration value="objectArray"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="super">
        <xs:simpleType>
          <xs:restriction base="xs:string"/>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="_isAbstract">
        <xs:simpleType>
          <xs:restriction base="xs:boolean"/>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="isKey">
        <xs:simpleType>
          <xs:restriction base="xs:boolean"/>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="foreignKey">
        <xs:simpleType>
          <xs:restriction base="xs:boolean"/>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="objectRef">
        <xs:simpleType>
          <xs:restriction base="xs:string"/>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="validator">
    <xs:complexType>
      <xs:choice maxOccurs="unbounded">
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="attr"/>
      </xs:choice>
      <xs:attribute name="package">
        <xs:simpleType>
          <xs:restriction base="xs:string"/>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="name">
        <xs:simpleType>
          <xs:restriction base="xs:string"/>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="type">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="required"/>
            <xs:enumeration value="regex"/>
            <xs:enumeration value="numeric"/>
            <xs:enumeration value="length"/>
            <xs:enumeration value="array"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="super">
        <xs:simpleType>
          <xs:restriction base="xs:string"/>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="mask"/>
      <xs:attribute name="min">
        <xs:simpleType>
          <xs:restriction base="xs:integer"/>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="max">
        <xs:simpleType>
          <xs:restriction base="xs:integer"/>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="minSize">
        <xs:simpleType>
          <xs:restriction base="xs:integer"/>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="maxSize">
        <xs:simpleType>
          <xs:restriction base="xs:integer"/>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Draagon/draagon-metaobjects/core/src/test/resources/metadata/test/produce/v1/meta.fruit.overlay.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>

<!-- Sample Overlay Example -->
<metadata
        xmlns="https://draagon.com/schema/metamodel/produce/v1"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://draagon.com/schema/metamodel/produce/v1 produce-v1-model.xsd"
        package="produce::v1">

    <!-- Custom Extension -->
    <object package="::container::ext" name="ProduceExt" isEmbedded="true">

        <!-- Name -->
        <field name="name" super="..::..::common::name"/>

        <!-- Foo Double -->
        <field name="foo" subType="double"/>

    </object>

    <!-- Overlay just for Apple -->
    <object package="::fruit" name="Apple">

        <!-- Special Overlay -->
        <field name="specialOverlay" subType="string"/>

    </object>

    <!-- Overlay for a container -->
    <object package="::container" name="Basket">

        <!-- Special Overlay -->
        <field name="specialOverlay" subType="string"/>

        <!-- Special Extension -->
        <field name="specialExt" subType="object" objectRef="::ext::ProduceExt"/>

    </object>

</metadata>

=== Draagon/draagon-metaobjects/core/src/test/resources/metadata/test/produce/v1/meta.common.xml
<metadata
        xmlns="https://draagon.com/schema/metamodel/produce/v1"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://draagon.com/schema/metamodel/produce/v1 produce-v1-model.xsd"
        package="produce::v1::common">

    <attr name="farmName">Big Bob's Farm</attr>

    <!-- Id -->
    <field name="id" subType="long" validation="required">
        <validator name="required" subType="required"/>
    </field>

    <!-- Name -->
    <field name="name" subType="string" validation="required,length">
        <validator name="required" subType="required"/>
        <validator name="length" subType="length">
            <attr subType="int" name="min">1</attr>
            <attr name="max">50</attr>
        </validator>
    </field>

</metadata>

=== Draagon/draagon-metaobjects/core/src/test/resources/metadata/test/produce/v1/meta.fruit.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>

<metadata
        xmlns="https://draagon.com/schema/metamodel/produce/v1"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://draagon.com/schema/metamodel/produce/v1 produce-v1-model.xsd"
        package="produce::v1::fruit">

    <!-- Fruit -->
    <object name="Fruit" subType="pojo" _isAbstract="true">

        <key name="primary" keys="id"/>
        <key subType="foreign" name="basketKey" keys="basketId" foreignObjectRef="..::container::Basket"/>

        <attr name="object">com.draagon.meta.test.produce.v1.Fruit</attr>

        <!-- Id -->
        <field name="id" super="..::common::id"/>

        <!-- Name -->
        <field name="name" super="..::common::name"/>

        <!-- BasketId -->
        <field name="basketId" super="..::common::id"/>

        <!-- Length -->
        <field name="length" subType="int"/>

        <!-- Weight -->
        <field name="weight" subType="int"/>
     
    </object>

    <!-- Apple -->
    <object name="Apple" super="Fruit" object="com.draagon.meta.test.produce.v1.Apple">

        <!-- attr name="object">com.draagon.meta.test.produce.v1.Apple</attr -->

        <!-- Orachard -->
        <field name="orchard" subType="string"/>

        <!-- Worms -->
        <field name="worms" subType="short"/>
      
    </object>  

    <!-- Macintosh -->
    <object name="Macintosh" super="Apple">

        <attr name="object">com.draagon.meta.test.produce.v1.Macintosh</attr>

    </object>

    <!-- Orange -->
    <object name="Orange" super="Fruit">

        <attr name="object">com.draagon.meta.test.produce.v1.Orange</attr>

        <field name="pickedDate" subType="date"/>
           
    </object>

</metadata>
