=== Draagon/draagon-metaobjects/core/src/main/resources/com/draagon/meta/loader/xml/types-config.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://www.draagon.com"
           xmlns="https://www.draagon.com"
           elementFormDefault="qualified">

    <xs:element name="typesConfig">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="types" type="typesDef" minOccurs="0" />
                <xs:element name="rules" type="rulesDef" minOccurs="0" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="typesDef">
        <xs:sequence>
            <xs:element name="type"  maxOccurs="unbounded" type="typeDef"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="typeDef">
        <xs:sequence>
            <xs:element name="children" minOccurs="0" type="childrenDef" />
            <xs:element name="subType" minOccurs="0" maxOccurs="unbounded" type="subTypeDef" />
        </xs:sequence>
        <xs:attribute name="name" type="typeNameDef" use="required"/>
        <xs:attribute name="class" type="classDef" use="required"/>
        <xs:attribute name="defaultSubType" type="defSubTypeNameDef"/>
        <xs:attribute name="defaultName" type="typeNameDef"/>
        <xs:attribute name="defaultNamePrefix" type="typeNameDef"/>
    </xs:complexType>

    <xs:complexType name="subTypeDef">
        <xs:sequence>
            <xs:element name="children" minOccurs="0" type="childrenDef"/>
        </xs:sequence>
        <xs:attribute name="name" type="metaDataNameDef" use="required"/>
        <xs:attribute name="class" type="classDef" use="required"/>
    </xs:complexType>

    <xs:complexType name="childrenDef">
        <xs:choice>
            <xs:element name="child" maxOccurs="unbounded" type="childDef"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="childDef">
        <xs:attribute name="type" type="typeNameDef" use="required"/>
        <xs:attribute name="subType" type="subTypeNameDef" use="required"/>
        <xs:attribute name="name" type="metaDataNameDef" use="required"/>
        <xs:attribute name="nameAliases" type="typeNameArrayDef"/>
        <xs:attribute name="required" type="xs:boolean" />
        <xs:attribute name="autoCreate" type="xs:boolean" />
        <xs:attribute name="defaultValue" type="xs:string" />
        <xs:attribute name="minValue" type="xs:int" />
        <xs:attribute name="maxValue" type="xs:int" />
        <xs:attribute name="inlineAttr" type="inlineAttrDef"/>
        <xs:attribute name="inlineAttrName" type="subTypeDef"/>
        <xs:attribute name="inlineAttrValueMap" type="xs:string"/>
    </xs:complexType>

    <xs:simpleType name="baseNameDef">
        <xs:restriction base="xs:string">
            <xs:pattern value="[_a-zA-Z/*]([a-zA-Z0-9_/-])*"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="typeNameDef">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z]([a-zA-Z0-9_/-])*"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="defSubTypeNameDef">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z]([a-zA-Z0-9_/-])*"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="subTypeNameDef">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z/*]([a-zA-Z0-9_/-])*"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="metaDataNameDef">
        <xs:restriction base="baseNameDef"/>
    </xs:simpleType>

    <xs:simpleType name="typeNameArrayDef">
        <xs:restriction base="xs:string">
            <xs:pattern value="([_a-zA-Z/*]([a-zA-Z0-9/-])*)([,_a-zA-Z/*]([a-zA-Z0-9/-])*)"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="classDef">
        <xs:restriction base="xs:string">
            <xs:pattern value="([\p{L}_$][\p{L}\p{N}_$]*\.)*[\p{L}_$][\p{L}\p{N}_$]*"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="inlineAttrDef">
        <xs:restriction base="xs:string">
            <xs:enumeration value="optional"/>
            <xs:enumeration value="required"/>
            <xs:enumeration value="illegal"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="rulesDef">
        <xs:sequence>
            <xs:element name="rule" minOccurs="0" maxOccurs="unbounded" type="ruleDef"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ruleDef">
        <xs:attribute name="name" type="typeNameDef" use="required"/>
    </xs:complexType>

</xs:schema>

=== Draagon/draagon-metaobjects/core/src/main/resources/com/draagon/meta/loader/xml/metaobjects.types.xml
<?xml version="1.0" encoding="UTF-8" ?>
<typesConfig
        xmlns="https://www.draagon.com"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://www.draagon.com/types/v2 types-config.xsd">

    <types>

        <type name="metadata" class="com.draagon.meta.MetaData" >
            <children>
                <child type="object" subType="*" name="*"/>
                <child type="field" subType="*" name="*"/>
                <child type="validator" subType="*" name="*"/>
            </children>
        </type>

        <type name="attr" class="com.draagon.meta.attr.MetaAttribute" defaultSubType="string">
            <subType name="string"       class="com.draagon.meta.attr.StringAttribute" />
            <subType name="stringArray"  class="com.draagon.meta.attr.StringArrayAttribute" />
            <subType name="properties"   class="com.draagon.meta.attr.PropertiesAttribute" />
            <subType name="class"        class="com.draagon.meta.attr.ClassAttribute" />
            <subType name="boolean"      class="com.draagon.meta.attr.BooleanAttribute" />
            <subType name="int"          class="com.draagon.meta.attr.IntAttribute" />
        </type>

        <type name="object" class="com.draagon.meta.object.MetaObject" defaultSubType="value">
            <children>
                <child type="attr" subType="boolean" name="_isAbstract"/>
                <child type="attr" subType="boolean" name="isInterface"/>
                <child type="key" subType="primary" name="primary"/>
                <child type="key" subType="secondary" name="*"/>
                <child type="key" subType="foreign" name="*"/>
                <child type="field" subType="*" name="*"/>
            </children>
            <subType name="pojo" class="com.draagon.meta.object.pojo.PojoMetaObject">
                <children>
                    <child type="attr" subType="string" name="object"/> <!-- required="true" inlineAttr="optional" / -->
                </children>
            </subType>
            <subType name="map" class="com.draagon.meta.object.mapped.MappedMetaObject">
                <children>
                    <child type="attr" subType="string" name="object"/>
                </children>
            </subType>
            <subType name="proxy" class="com.draagon.meta.object.proxy.ProxyMetaObject">
                <children>
                    <child type="attr" subType="string" name="object"/>
                    <child type="attr" subType="string" name="proxyObject"/>
                </children>
            </subType>
            <subType name="data" class="com.draagon.meta.object.data.DataMetaObject">
                <children>
                    <child type="attr" subType="string" name="object"/> <!-- autoCreate="true" inlineAttr="optional" defaultValue="com.draagon.meta.object.value.ValueObject"/ -->
                </children>
            </subType>
            <subType name="value" class="com.draagon.meta.object.value.ValueMetaObject">
                <children>
                    <child type="attr" subType="string" name="object"/> <!-- autoCreate="true" inlineAttr="optional" defaultValue="com.draagon.meta.object.value.ValueObject"/ -->
                </children>
            </subType>
        </type>

        <type name="key" class="com.draagon.meta.key.MetaKey" defaultSubType="primary">
            <children>
                <child type="attr" subType="stringArray" name="keys"/>
            </children>
            <subType name="primary" class="com.draagon.meta.key.PrimaryKey"/>
            <subType name="secondary" class="com.draagon.meta.key.SecondaryKey"/>
            <subType name="foreign" class="com.draagon.meta.key.ForeignKey">
                <children>
                    <child type="attr" subType="string" name="foreignObjectRef"/>
                    <child type="attr" subType="string" name="foreignKey"/>
                </children>
            </subType>
        </type>

        <type name="field" class="com.draagon.meta.field.MetaField" defaultSubType="string">
            <children>
                <child type="attr" subType="boolean" name="_isAbstract"/>
                <child type="attr" subType="string" name="objectRef"/>
                <child type="attr" subType="stringArray" name="validation"/>
                <child type="attr" subType="string" name="defaultValue"/>
                <child type="validator" subType="*" name="*"/>
            </children>
            <subType name="boolean"      class="com.draagon.meta.field.BooleanField" />
            <subType name="byte"         class="com.draagon.meta.field.ByteField" />
            <subType name="short"        class="com.draagon.meta.field.ShortField" />
            <subType name="int"          class="com.draagon.meta.field.IntegerField" />
            <subType name="long"         class="com.draagon.meta.field.LongField" />
            <subType name="float"        class="com.draagon.meta.field.FloatField" />
            <subType name="double"       class="com.draagon.meta.field.DoubleField" />
            <subType name="string"       class="com.draagon.meta.field.StringField" />
            <subType name="date"         class="com.draagon.meta.field.DateField" />

            <!-- subType name="booleanArray" class="com.draagon.meta.field.BooleanArrayField" />
            <subType name="byteArray"    class="com.draagon.meta.field.ByteArrayField" />
            <subType name="intArray"     class="com.draagon.meta.field.IntegerArrayField" />
            <subType name="longArray"    class="com.draagon.meta.field.LongArrayField" />
            <subType name="floatArray"   class="com.draagon.meta.field.FloatArrayField" />
            <subType name="doubleArray"  class="com.draagon.meta.field.DoubleArrayField" / -->
            <subType name="stringArray"  class="com.draagon.meta.field.StringArrayField"/>
            <!-- subType name="dateArray"    class="com.draagon.meta.field.DateArrayField" /-->
            <subType name="object"       class="com.draagon.meta.field.ObjectField"/>
            <subType name="objectArray"  class="com.draagon.meta.field.ObjectArrayField"/>
        </type>

        <type name="validator"  class="com.draagon.meta.validator.MetaValidator" defaultSubType="required" defaultNamePrefix="validator">
            <subType name="required" class="com.draagon.meta.validator.RequiredValidator"/>
            <subType name="regex" class="com.draagon.meta.validator.RegexValidator">
                <children>
                    <child type="attr" subType="regex" name="mask"/> <!-- inlineAttr="optional" required="true"/ -->
                </children>
            </subType>
            <subType name="numeric" class="com.draagon.meta.validator.NumericValidator" />
            <subType name="length" class="com.draagon.meta.validator.LengthValidator" >
                <children>
                    <child type="attr" subType="int" name="min"/> <!-- inlineAttr="optional" autoCreate="true" defaultValue="0" minValue="0"/ -->
                    <child type="attr" subType="int" name="max"/> <!-- inlineAttr="optional" required="true" minValue="0"/-->
                </children>
            </subType>
            <subType name="array" class="com.draagon.meta.validator.ArrayValidator" >
                <children>
                    <child type="attr" subType="int" name="minSize"/>
                    <child type="attr" subType="int" name="maxSize"/>
                </children>
            </subType>
        </type>
    </types>

    <!-- Rules -->
    <!-- rules>
        <rule name="todo: add rules"/>
    </rules -->

</typesConfig>

=== Draagon/draagon-metaobjects/metadata/src/main/resources/com/draagon/meta/loader/simple/simple.types.xml
<?xml version="1.0" encoding="UTF-8" ?>
<typesConfig
        xmlns="https://www.draagon.com/types/v2"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://www.draagon.com/types/v2 ../types/types-config.xsd">

    <types>

        <type name="metadata" class="com.draagon.meta.MetaData" >
            <children>
                <child type="object" subType="*" name="*"/>
                <child type="field" subType="*" name="*"/>
                <child type="validator" subType="*" name="*"/>
            </children>
        </type>

        <type name="attr" class="com.draagon.meta.attr.MetaAttribute" defaultSubType="string">
            <subType name="string"       class="com.draagon.meta.attr.StringAttribute" />
            <subType name="stringArray"  class="com.draagon.meta.attr.StringArrayAttribute" />
            <subType name="properties"   class="com.draagon.meta.attr.PropertiesAttribute" />
            <subType name="class"        class="com.draagon.meta.attr.ClassAttribute" />
            <subType name="boolean"      class="com.draagon.meta.attr.BooleanAttribute" />
            <subType name="int"          class="com.draagon.meta.attr.IntAttribute" />
        </type>

        <type name="object" class="com.draagon.meta.object.MetaObject" defaultSubType="map">
            <children>
                <child type="attr" subType="boolean" name="_isAbstract"/>
                <child type="attr" subType="boolean" name="isInterface"/>
                <child type="attr" subType="boolean" name="isKey"/>
                <child type="field" subType="*" name="*"/>
            </children>
            <subType name="pojo" class="com.draagon.meta.object.pojo.PojoMetaObject">
                <children>
                    <child type="attr" subType="string" name="object"/>
                </children>
            </subType>
            <subType name="map" class="com.draagon.meta.object.mapped.MappedMetaObject">
                <children>
                    <child type="attr" subType="string" name="object"/>
                </children>
            </subType>
            <subType name="proxy" class="com.draagon.meta.object.proxy.ProxyMetaObject">
                <children>
                    <child type="attr" subType="string" name="object"/>
                    <child type="attr" subType="String" name="proxyObject"/>
                </children>
            </subType>
        </type>

        <type name="field" class="com.draagon.meta.field.MetaField" defaultSubType="string">
            <children>
                <child type="attr" subType="boolean" name="_isAbstract"/> <!-- inlineAttr="required" / -->
                <child type="validator" subType="*" name="*"/>
            </children>
            <subType name="boolean"      class="com.draagon.meta.field.BooleanField" />
            <subType name="byte"         class="com.draagon.meta.field.ByteField" />
            <subType name="short"        class="com.draagon.meta.field.ShortField" />
            <subType name="int"          class="com.draagon.meta.field.IntegerField" />
            <subType name="long"         class="com.draagon.meta.field.LongField" />
            <subType name="float"        class="com.draagon.meta.field.FloatField" />
            <subType name="double"       class="com.draagon.meta.field.DoubleField" />
            <subType name="string"       class="com.draagon.meta.field.StringField" />
            <subType name="date"         class="com.draagon.meta.field.DateField" />
            <subType name="class"        class="com.draagon.meta.field.ClassField" />
            <!-- subType name="booleanArray" class="com.draagon.meta.field.BooleanArrayField" />
            <subType name="byteArray"    class="com.draagon.meta.field.ByteArrayField" />
            <subType name="intArray"     class="com.draagon.meta.field.IntegerArrayField" />
            <subType name="longArray"    class="com.draagon.meta.field.LongArrayField" />
            <subType name="floatArray"   class="com.draagon.meta.field.FloatArrayField" />
            <subType name="doubleArray"  class="com.draagon.meta.field.DoubleArrayField" / -->
            <subType name="stringArray"  class="com.draagon.meta.field.StringArrayField"/>
            <!-- subType name="dateArray"    class="com.draagon.meta.field.DateArrayField" /-->
            <subType name="object"       class="com.draagon.meta.field.ObjectField">
                <children>
                    <child type="attr" subType="string" name="objectRef"/>
                </children>
            </subType>
            <subType name="objectArray"  class="com.draagon.meta.field.ObjectArrayField" >
                <children>
                    <child type="attr" subType="string" name="objectRef"/>
                </children>
            </subType>
        </type>

        <type name="validator"  class="com.draagon.meta.validator.MetaValidator" defaultSubType="required" defaultNamePrefix="validator">
            <subType name="required" class="com.draagon.meta.validator.RequiredValidator"/>
            <subType name="regex" class="com.draagon.meta.validator.RegexValidator">
                <children>
                    <child type="attr" subType="regex" name="mask"/> <!-- inlineAttr="optional" required="true"/ -->
                </children>
            </subType>
            <subType name="numeric" class="com.draagon.meta.validator.NumericValidator" />
            <subType name="length" class="com.draagon.meta.validator.LengthValidator" >
                <children>
                    <child type="attr" subType="int" name="min"/> <!-- inlineAttr="optional" autoCreate="true" defaultValue="0" minValue="0"/ -->
                    <child type="attr" subType="int" name="max"/> <!-- inlineAttr="optional" required="true" minValue="0"/-->
                </children>
            </subType>
        </type>
    </types>

</typesConfig>
